# Week 3: 

### Table of Contents

1. [Intialize an array](#bullet1)
2. [Operations with arrays](#bullet2)
3. [Converting a list to an array](#bullet3)
4. [Nested arrays](bullet#4)
5. [Shortcuts](#bullet5)
6. [dtype attribute](#bullet6)
7. [Indexing and Slicing](#bullet7)
8. [.copy function](#bullet8)
9. [Boolean Indexing](#bullet9)
10. [Transposing Arrays](#bullet10)
11. [Uniform and Standard Normal Distributions](#bullet11)
12. [Universal Functions](#bullet12)
13. [np.where](#bullet13)
14. [Mathematical and Statistical Methods](#bullet14)
15. [Methods for Boolean arrays](#bullet15)
16. [Sorting](#bullet16)
17. [Unique](#bullet17)
18. [Linear Algebra](#bullet18)

## 1. Intialize an array <a class="anchor" id="bullet1"></a>

In [1]:
## importing necessary libraries
import numpy as np 

One of the features of NumPy is its N-dimensional array object. 

In [2]:
# use np.array to intialize a new ndarray object
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [3]:
arr2 = np.array([[10, 20, 30], [5, 10, 15], [1, 1, 1]]) # nested array or a matrix in this case
print(arr2)

[[10 20 30]
 [ 5 10 15]
 [ 1  1  1]]


## 2. Operations with arrays <a class="anchor" id="bullet2"></a>

In [4]:
# can scale an entire ndarray
arr1 * 10

array([10, 20, 30, 40, 50])

In [5]:
# can scale an entire ndarray
arr2 / 5

array([[2. , 4. , 6. ],
       [1. , 2. , 3. ],
       [0.2, 0.2, 0.2]])

In [6]:
# can add/subtract a value to every element in an entire ndarray
arr1 + 1

array([2, 3, 4, 5, 6])

In [7]:
arr2 - 1

array([[ 9, 19, 29],
       [ 4,  9, 14],
       [ 0,  0,  0]])

In [8]:
# can add/subtract arrays of the same dimension
arr1 + arr1

array([ 2,  4,  6,  8, 10])

In [9]:
arr2 + arr2

array([[20, 40, 60],
       [10, 20, 30],
       [ 2,  2,  2]])

In [10]:
arr1 - arr1

array([0, 0, 0, 0, 0])

In [11]:
arr2 - arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
# what happens if you try to add/subtract arrays of different dimensions?
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (5,) (3,3) 

In [13]:
arr1 - arr2

ValueError: operands could not be broadcast together with shapes (5,) (3,3) 

In [14]:
# same rules apply for multiplication and division

In [15]:
arr1 * arr1

array([ 1,  4,  9, 16, 25])

In [16]:
arr2 * arr2

array([[100, 400, 900],
       [ 25, 100, 225],
       [  1,   1,   1]])

In [17]:
arr1 / arr1

array([1., 1., 1., 1., 1.])

In [18]:
arr2 / arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# can raise every element in an array to some power
arr2 ** 2

array([[100, 400, 900],
       [ 25, 100, 225],
       [  1,   1,   1]])

In [20]:
arr1 ** 4

array([  1,  16,  81, 256, 625])

In [21]:
# can compare arrays of the sam size

In [22]:
# in this example we will compare arr1 to temp

In [23]:
temp = [5, 1, 2, 3, 4]

In [24]:
arr1 > temp

array([False,  True,  True,  True,  True])

Based off the error, the arrays have different dimensions, or specifically, shapes. Shape is an attribute of ndarrays. Attributes consist of a name (shape) and a value (dimensions) that describe the object. 

In [25]:
print(arr1.shape)
arr2.shape

(5,)


(3, 3)

## 3. Converting a list to an array <a class="anchor" id="bullet3"></a>

In [26]:
lst = [2, 4, 5, 2, 3, 8]
type(lst)

list

In [27]:
arr3 = np.array(lst)
type(arr3)

numpy.ndarray

## 4. Nested array <a class="anchor" id="bullet4"></a>

In [28]:
# arr2 is an example of a nested array, specifically a matrix
print(arr2)

[[10 20 30]
 [ 5 10 15]
 [ 1  1  1]]


In [29]:
# other examples of nested arrays

In [30]:
arr4 = np.array([[1, 3, 5], [7, 9, 11]])
print(arr4)

[[ 1  3  5]
 [ 7  9 11]]


In [31]:
arr5 = np.array([[1, 3, 5], [7, 9]])
print(arr5)
# nested sequences should be a list of EQUAL-LENGTH lists

[list([1, 3, 5]) list([7, 9])]


/var/folders/q_/ggw8wr5d7n3b1_xgl5z2xn340000gn/T/ipykernel_9670/3359908876.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr5 = np.array([[1, 3, 5], [7, 9]])


In [32]:
# attributes of a nested array
print(arr2.ndim)
arr2.shape

2


(3, 3)

In [33]:
print(arr4.ndim)
arr4.shape

2


(2, 3)

## 5. Shortcuts! <a class="anchor" id="bullet5"></a>

In [34]:
# create a ndarray of 5 0s
arr6 = np.zeros(5)
print(arr6)

[0. 0. 0. 0. 0.]


In [35]:
# create a ndarray of 10 1s
arr7 = np.ones(10)
print(arr7)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [36]:
# create an identity matrix of size 2 by 2
arr8 = np.identity(2)
print(arr8)

[[1. 0.]
 [0. 1.]]


The following demonstrates different ways of using np.arange to create lists. 

In [37]:
arr9 = np.arange(10) 
print(arr9)

[0 1 2 3 4 5 6 7 8 9]


In [38]:
arr10 = np.arange(1, 10)
print(arr10)

[1 2 3 4 5 6 7 8 9]


In [39]:
arr11 = np.arange(1, 10, 2)
print(arr11)

[1 3 5 7 9]


## 6. dtype attribute <a class="anchor" id="bullet6"></a>

The dtype or data type tells us information about the kind of fata the ndarray holds.

In [40]:
print(arr7)
arr7.dtype

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


dtype('float64')

In [41]:
print(arr10)
arr10.dtype

[1 2 3 4 5 6 7 8 9]


dtype('int64')

One can used the method, astype, to convert or cast a ndarray's data from one type to another. 

In [42]:
arr7_temp = arr7.astype(np.int64)
print(arr7_temp)
arr7_temp.dtype

[1 1 1 1 1 1 1 1 1 1]


dtype('int64')

In [43]:
arr10_temp = arr10.astype(np.string_)
print(arr10_temp)
arr10_temp.dtype

[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9']


dtype('S21')

## 7. Index and Slicing <a class="anchor" id="bullet7"></a>

In [44]:
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# grabbing one element using its index
## in this case, grabbing the 3rd element
arr9[2]

2

In [46]:
# grabbing a range/subset of elements within the array
## format =[start:stop], does not include 'stop' index element
arr9[2:6]

array([2, 3, 4, 5])

In [47]:
# replace a value or range of values in the array
arr9[0] = 1
arr9[2:6] = 50
arr9

array([ 1,  1, 50, 50, 50, 50,  6,  7,  8,  9])

In [48]:
# other ways to slice
print(arr9[:2])
print(arr9[2:])

[1 1]
[50 50 50 50  6  7  8  9]


With higher dimensional arrays, there are more options for indexing/slicing

In [49]:
arr2

array([[10, 20, 30],
       [ 5, 10, 15],
       [ 1,  1,  1]])

In [50]:
# grabbing one whole element, in this case a list, from the nested array
arr2[1]

array([ 5, 10, 15])

In [51]:
# grabbing a specific value based off its index
arr2[1][1]

10

In [52]:
arr2[1, 1]

10

Think of the first indexing as to find the row and the second indexing to find the column.

In [53]:
# grabbing a column
arr2[:, 1:2]

array([[20],
       [10],
       [ 1]])

In [54]:
arr2[:, 1]

array([20, 10,  1])

In [55]:
# grabbing the first two elements of the row given columns
arr2[:2, :2]

array([[10, 20],
       [ 5, 10]])

## 8. .copy function <a class="anchor" id="bullet8"></a>

In [56]:
arr2

array([[10, 20, 30],
       [ 5, 10, 15],
       [ 1,  1,  1]])

In [57]:
# copies values in a duplicate, unrelated array
old_values = arr2[0].copy()

In [58]:
arr2[0] = 42
arr2

array([[42, 42, 42],
       [ 5, 10, 15],
       [ 1,  1,  1]])

In [59]:
arr2[0] = old_values
arr2

array([[10, 20, 30],
       [ 5, 10, 15],
       [ 1,  1,  1]])

## 9. Boolean Indexing <a class="anchor" id="bullet9"></a>

In [60]:
# can check based on a certain condition using boolean operators

In [61]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

In [62]:
names == "Joe"

array([False,  True, False, False, False,  True,  True])

In [63]:
arr9

array([ 1,  1, 50, 50, 50, 50,  6,  7,  8,  9])

In [64]:
arr9 >= 9 

array([False, False,  True,  True,  True,  True, False, False, False,
        True])

In [65]:
# this boolean array can be passed when indexing the array

In [66]:
names[names == "Joe"]

array(['Joe', 'Joe', 'Joe'], dtype='<U4')

In [67]:
arr9[arr9 >= 9]

array([50, 50, 50, 50,  9])

In [68]:
# can index columns too?? ASK NICK 

In [69]:
# different ways to negate:

print(names != "Joe")
print(~(names == "Joe"))

[ True False  True  True  True False False]
[ True False  True  True  True False False]


In [70]:
# to combine multiple booleans conditions, use % (and) and | (or)
mask = (names == "Joe") | (names == "Will")
mask

array([False,  True,  True, False,  True,  True,  True])

In [71]:
names[mask]

array(['Joe', 'Will', 'Will', 'Joe', 'Joe'], dtype='<U4')

## 10. Transposing Arrays <a class="anchor" id="bullet10"></a>

Transposing is a form of reshaping that swaps the axes.

In [72]:
arr12 = np.arange(15).reshape((3, 5))
arr12

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
arr12.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [74]:
# may use this for matrix computations such as calculating the inner matrix product

In [75]:
arr13 = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr13

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [76]:
print(np.dot(arr13.T, arr13))
arr13.T @ arr13

[[39 20 12]
 [20 14  2]
 [12  2 10]]


array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [77]:
# another way to transpose
arr12.swapaxes(0, 1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 11. Uniform and standard normal distributions <a class="anchor" id="bullet11"></a>

In [78]:
## not sure how to demonstrate this, do i use graphs? ASK NICK 

In [79]:
rng = np.random.default_rng(seed=3252)

In [80]:
s1 = rng.uniform(-1,0,1000)

In [81]:
s2 = rng.standard_normal(1000)

## 12. Universal Functions <a class="anchor" id="bullet12"></a>

"A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays." - _McKinney_

In [82]:
arr14 = np.arange(10)
arr14

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# unary ufuncs

In [84]:
np.sqrt(arr14)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [85]:
np.exp(arr14)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [86]:
# binary ufuncs

In [87]:
x = rng.standard_normal(8)
x

array([ 1.14241792, -0.28196877, -0.26848554,  1.10041352, -0.05589917,
        0.26693154,  0.15839299,  0.27169467])

In [88]:
y = rng.standard_normal(8)
y

array([ 0.31917679,  0.65604617, -1.35796733, -0.37204465,  1.72783776,
        0.12950675,  1.08868117, -0.28840552])

In [89]:
np.maximum(x, y)

array([ 1.14241792,  0.65604617, -0.26848554,  1.10041352,  1.72783776,
        0.26693154,  1.08868117,  0.27169467])

In [90]:
np.add(x, y)

array([ 1.46159471,  0.37407739, -1.62645287,  0.72836887,  1.6719386 ,
        0.39643828,  1.24707416, -0.01671085])

In [91]:
np.subtract(x, y)

array([ 0.82324113, -0.93801494,  1.08948179,  1.47245817, -1.78373693,
        0.13742479, -0.93028819,  0.56010019])

In [92]:
np.divide(x, y)

array([ 3.57926376, -0.4298002 ,  0.19771134, -2.95774585, -0.03235209,
        2.06114   ,  0.1454907 , -0.9420578 ])

In [93]:
np.multiply(x, y)

array([ 0.36463329, -0.18498453,  0.36459459, -0.40940296, -0.09658469,
        0.03456944,  0.17243946, -0.07835824])

In [94]:
np.floor_divide(x, y)

array([ 3., -1.,  0., -3., -1.,  2.,  0., -1.])

In [95]:
np.power(x, y)

/var/folders/q_/ggw8wr5d7n3b1_xgl5z2xn340000gn/T/ipykernel_9670/3398018405.py:1: RuntimeWarning: invalid value encountered in power
  np.power(x, y)


array([1.04341338,        nan,        nan, 0.96502673,        nan,
       0.84278135, 0.13451403, 1.45617687])

In [96]:
# and more... refer back to Mckinney for a complete list

## 13. np.where <a class="anchor" id="bullet13"></a>

In [97]:
arr15 = np.arange(2, 50, 2)
arr15

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

In [98]:
## not sure I understand this section 

## 14. Mathematical and Statistical Methods <a class="anchor" id="bullet14"></a>

"A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class." - *McKinney*

In [99]:
arr16 = rng.standard_normal((5, 4))
arr16

array([[ 0.5975821 ,  0.28150336,  0.66070948, -0.90722986],
       [-0.3010943 ,  1.80341062,  1.3912428 ,  0.74837662],
       [ 0.05843706,  0.31940698, -1.57074395,  0.28034852],
       [ 0.52380852,  1.7371232 , -1.18701463,  0.0993711 ],
       [-0.62912318, -2.41944318, -0.60629023, -0.58116553]])

In [100]:
arr16.mean()

0.014960774148855138

In [101]:
np.mean(arr16)

0.014960774148855138

In [102]:
arr16.sum()

0.29921548297710276

In [103]:
# Functions like mean and sum take an optional axis argument that computes the statistic over the given axis, resulting in an array with one less dimension:
# compute mean across the columns
arr16.mean(axis=1)

array([ 0.15814127,  0.91048393, -0.22813785,  0.29332205, -1.05900553])

In [104]:
# compute sum down the rows
arr16.sum(axis=0)

array([ 0.24961019,  1.72200099, -1.31209653, -0.36029916])

In [105]:
# Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results:
arr14

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
arr14.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [107]:
arr16.cumsum(axis=0) # computes along rows

array([[ 0.5975821 ,  0.28150336,  0.66070948, -0.90722986],
       [ 0.29648779,  2.08491398,  2.05195228, -0.15885324],
       [ 0.35492485,  2.40432097,  0.48120833,  0.12149527],
       [ 0.87873337,  4.14144417, -0.7058063 ,  0.22086637],
       [ 0.24961019,  1.72200099, -1.31209653, -0.36029916]])

In [108]:
arr16.cumsum(axis=1) # computes along columns

array([[ 0.5975821 ,  0.87908546,  1.53979494,  0.63256508],
       [-0.3010943 ,  1.50231632,  2.89355912,  3.64193574],
       [ 0.05843706,  0.37784405, -1.19289991, -0.91255139],
       [ 0.52380852,  2.26093172,  1.07391709,  1.17328819],
       [-0.62912318, -3.04856636, -3.65485659, -4.23602213]])

## 15. Methods for boolean arrays <a class="anchor" id="bullet15"></a>

Boolean values are coerced to 1 (True) and 0 (False) in the preceding methods. Thus, sum is often used as a means of counting True values in a Boolean array:

In [109]:
arr17 = rng.standard_normal(100)
arr17

array([ 0.23854279, -1.30910132, -1.15414648, -2.77686265, -0.6081114 ,
        0.42628168,  0.66712198,  1.61995501, -1.19303883,  2.20230492,
       -0.34297596, -1.14458212, -0.50349797,  1.00770884, -0.42501925,
        1.53495065, -0.94101425, -1.12659376,  0.40537201, -0.78479566,
       -0.6799847 , -0.86774519, -0.73035331,  0.01206533,  0.2021479 ,
       -0.38527559, -1.68006465,  0.17927304,  1.90459605, -0.02415435,
       -2.97610024,  0.76488787,  0.5578629 ,  0.46353059,  0.14302605,
       -0.59959207,  0.13155518, -0.17592927,  1.13342691, -0.72334268,
        1.12808542,  1.3926541 , -1.46715074, -1.07613555, -0.52978731,
       -1.89867968, -0.3958222 , -1.52575667,  0.02016304,  1.07301681,
        0.2638599 , -0.29240348, -0.29512487,  0.13702597,  0.02395526,
       -1.458959  ,  1.14139075, -0.26686555, -0.36662851,  0.43288428,
        0.00828527, -0.37618658, -0.2869308 , -0.69655434, -0.23958752,
        0.60002437,  0.43308239, -0.36574687, -0.02459358,  0.55

In [110]:
(arr17 > 0).sum() # Number of positive values

42

In [111]:
(arr17 <= 0).sum() # Number of non-positive values

58

Two additional methods, any and all, are useful especially for Boolean arrays. any tests whether one or more values in an array is True, while all checks if every value is True:

In [112]:
bools = np.array([False, False, True, False])

print(bools.any())
bools.all()

True


False

These methods also work with non-Boolean arrays, where nonzero elements are treated as True.

## 16. Sorting <a class="anchor" id="bullet16"></a>

In [113]:
arr18 = rng.standard_normal(6)
arr18

array([ 0.5872965 ,  1.46189064, -0.26993541,  1.51737643, -0.91751874,
       -0.69139623])

In [114]:
arr18.sort()
arr18

array([-0.91751874, -0.69139623, -0.26993541,  0.5872965 ,  1.46189064,
        1.51737643])

In [115]:
# multidimensional sorting
arr19 = rng.standard_normal((5, 3))
arr19

array([[ 1.37613133, -0.4740934 , -0.39577908],
       [-0.65298439,  2.02218852, -0.07984649],
       [-0.95380272,  0.05534965,  0.0057336 ],
       [-0.41212907,  0.59028033, -0.42022751],
       [ 2.1818843 ,  0.37009795, -1.80932207]])

In [116]:
arr19.sort(axis=0) # sort within each column
arr19

array([[-0.95380272, -0.4740934 , -1.80932207],
       [-0.65298439,  0.05534965, -0.42022751],
       [-0.41212907,  0.37009795, -0.39577908],
       [ 1.37613133,  0.59028033, -0.07984649],
       [ 2.1818843 ,  2.02218852,  0.0057336 ]])

In [117]:
arr19.sort(axis=1) # sort across each row
arr19

array([[-1.80932207, -0.95380272, -0.4740934 ],
       [-0.65298439, -0.42022751,  0.05534965],
       [-0.41212907, -0.39577908,  0.37009795],
       [-0.07984649,  0.59028033,  1.37613133],
       [ 0.0057336 ,  2.02218852,  2.1818843 ]])

The top-level method numpy.sort returns a sorted copy of an array (like the Python built-in function sorted) instead of modifying the array in place. For example:

In [118]:
arr20 = np.array([5, -10, 7, 1, 0, -3])
arr20

array([  5, -10,   7,   1,   0,  -3])

In [119]:
sorted_arr20 = np.sort(arr20)
sorted_arr20

array([-10,  -3,   0,   1,   5,   7])

## 17. Unique <a class="anchor" id="bullet17"></a>

In [120]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [121]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [122]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])

In [123]:
np.unique(ints)

array([1, 2, 3, 4])

In [124]:
# pure python alternative:
sorted(set(names))

['Bob', 'Joe', 'Will']

Another function, numpy.in1d, tests membership of the values in one array in another, returning a Boolean array:

In [125]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
values

array([6, 0, 0, 3, 2, 5, 6])

In [126]:
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## 18. Linear Algebra <a class="anchor" id="bullet18"></a>

In [127]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [128]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [129]:
x.dot(y) # == np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [130]:
# importing inverse and determinant functions
from numpy.linalg import inv, qr

X = rng.standard_normal((5, 5))
X

array([[-0.99964764,  0.27121979,  0.2615495 , -0.40614748,  0.29957505],
       [-1.03007853,  0.02724933,  0.07251864,  0.8134973 ,  0.22825615],
       [ 0.6629406 , -0.67142736, -1.38924924,  0.3837671 ,  0.26852461],
       [ 0.90694772,  0.37393356,  0.30201629,  0.63940787, -0.21934853],
       [-0.53134316,  0.32450794,  0.22476238,  1.14858811, -0.90642337]])

In [131]:
mat = X.T @ X
mat

array([[ 3.60472713, -0.57759652, -1.10265992, -0.20793187, -0.07389119],
       [-0.57759652,  0.77024912,  1.19156465,  0.26616231, -0.46898762],
       [-1.10265992,  1.19156465,  2.14541252, -0.12911111, -0.54811779],
       [-0.20793187,  0.26616231, -0.12911111,  2.70210789, -1.01429526],
       [-0.07389119, -0.46898762, -0.54811779, -1.01429526,  1.08366865]])

In [132]:
inv(mat)

array([[ 0.38667244, -0.24513565,  0.42776131,  0.19367725,  0.31791599],
       [-0.24513565, 15.77424496, -8.79399367, -1.70536966,  0.76584258],
       [ 0.42776131, -8.79399367,  5.73630021,  1.3021957 ,  0.34356692],
       [ 0.19367725, -1.70536966,  1.3021957 ,  0.91009652,  0.78564327],
       [ 0.31791599,  0.76584258,  0.34356692,  0.78564327,  2.18503254]])

In [133]:
mat @ inv(mat)

array([[ 1.00000000e+00, -5.27873423e-16,  1.40302242e-15,
         1.36483996e-16, -8.02717149e-17],
       [-1.68290081e-17,  1.00000000e+00,  2.28740480e-15,
         6.69834089e-16,  9.88953104e-17],
       [-2.01295638e-16,  2.28041497e-15,  1.00000000e+00,
         5.46098920e-18,  2.28282174e-16],
       [-6.77078316e-17,  1.81425617e-15, -2.68022934e-16,
         1.00000000e+00,  2.81700605e-17],
       [ 4.56108311e-17, -1.63053403e-15,  4.38489629e-16,
         6.07017299e-17,  1.00000000e+00]])

In [134]:
# and more... refer back to Mckinney for a complete list